spring.jpa:
  database: mysql
  hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: create
  show-sql: true
  properties:
    hibernate:
        format_sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:mysql://my-rds.cp74kiovk3na.ap-northeast-2.rds.amazonaws.com:3306/tto?serverTimezone=Asia/Seoul
  username: admin
  password: gudwls124!
  driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: tto-security-with-jwt-study-secret-key
  access-token-expired-time-ms: 30000
  refresh-token-expired-time-ms: 600000
#  refresh-token-expired-time-ms: 1200000






